services:
  - type: web
    name: tiktok-video-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    region: oregon
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
